package com.happybananas.tracezilla.shopify;
import com.fasterxml.jackson.databind.JsonNode;import java.util.*;
public final class ShopifyLocationService {
 public static final String QUERY="query GetLocations($first: Int!, $after: String) { locations(first: $first, after: $after) { nodes { id legacyResourceId name isActive hasActiveInventory fulfillsOnlineOrders address { address1 address2 city province country zip } } pageInfo { hasNextPage endCursor } } }";
 private final ShopifyClient client; public ShopifyLocationService(ShopifyClient client){this.client=client;}
 public List<ShopifyLocation> read() throws Exception {var result=new ArrayList<ShopifyLocation>();String after=null;var seen=new HashSet<String>();while(true){var variables=new HashMap<String,Object>();variables.put("first",250);variables.put("after",after);var payload=client.graphql(QUERY,variables);var connection=payload.path("data").path("locations");if(!connection.isObject()||!connection.path("nodes").isArray()||!connection.path("pageInfo").isObject())throw new IllegalStateException("Shopify response is missing locations.");for(var node:connection.path("nodes"))result.add(map(node));var page=connection.path("pageInfo");if(!page.path("hasNextPage").isBoolean())throw new IllegalStateException("Shopify returned invalid location pagination data.");if(!page.path("hasNextPage").asBoolean())break;after=page.path("endCursor").asText("");if(after.isBlank()||!seen.add(after))throw new IllegalStateException("Shopify returned an invalid or repeated location cursor.");}return result;}
 public static ShopifyLocation map(JsonNode value){String id=required(value,"id"),legacy=required(value,"legacyResourceId"),name=required(value,"name");boolean active=bool(value,"isActive"),inventory=bool(value,"hasActiveInventory"),orders=bool(value,"fulfillsOnlineOrders");var raw=value.path("address");var address=new LinkedHashMap<String,String>();for(var key:List.of("address1","address2","city","province","country","zip")){var field=raw.path(key);address.put(key,field.isMissingNode()||field.isNull()||field.asText().isBlank()?null:field.asText().trim());}return new ShopifyLocation(id,legacy,name,active,inventory,orders,address);}
 private static String required(JsonNode value,String key){var field=value.path(key);if(field.isMissingNode()||field.isNull()||field.asText().isBlank())throw new IllegalArgumentException("Shopify location field ["+key+"] is required.");return field.asText().trim();}
 private static boolean bool(JsonNode value,String key){var field=value.path(key);if(!field.isBoolean())throw new IllegalArgumentException("Shopify location field ["+key+"] must be boolean.");return field.asBoolean();}
}
